spring.application.name=${APPLICATION_NAME}
spring.datasource.url=jdbc:mysql://localhost/${DATABASE_NAME}?createDatabaseIfNotExist=true
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}

telegram.token=${TELEGRAM_TOKEN}

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret={STRIPE_WEBHOOK_SECRET}

payment.scheduler.interval=${PAYMENT_SCHEDULER_INTERVAL}
rental.scheduler.interval=${RENTAL_SCHEDULER_INTERVAL}
rental.scheduler.message.repeat=${RENTAL_SCHEDULER_MESSAGE_REPEAT}
